export enum FeeType {
  MONTHLY = 'monthly',
  DAILY = 'daily',
  WEEKLY = 'weekly',
  HOURLY = 'hourly',
  PER_BATCH = 'per_batch',
  PER_SESSION = 'per_session',
  AGE_BASED = 'age_based',
  COACH_LICENSE_BASED = 'coach_license_based',
  PLAYER_LEVEL_BASED = 'player_level_based',
  SEASONAL = 'seasonal',
  PACKAGE_BASED = 'package_based',
  GROUP_DISCOUNT = 'group_discount',
  ADVANCE_BOOKING = 'advance_booking',
  WEEKEND_PRICING = 'weekend_pricing',
  PEAK_HOURS = 'peak_hours',
  MEMBERSHIP_BASED = 'membership_based',
  CUSTOM = 'custom',
}

