export enum Section {
  COACHING_CENTER = 'coaching_center',
  EMPLOYEE = 'employee',
  BATCH = 'batch',
  BOOKING = 'booking',
  STUDENT = 'student',
  PARTICIPANT = 'participant',
  SPORT = 'sport',
  FACILITY = 'facility',
  LOCATION = 'location',
  SETTINGS = 'settings',
  REEL = 'reel',
  ROLE = 'role',
  USER = 'user',
  OPERATIONAL_USER = 'operational_user',
  ACADEMY_AUTH = 'academy_auth',
  USER_AUTH = 'user_auth',
  PERMISSION = 'permission',
  DASHBOARD = 'dashboard',
  TRANSACTION = 'transaction',
  PAYMENT = 'payment',
  BANNER = 'banner',
  CMS_PAGE = 'cms_page',
  NOTIFICATION = 'notification',
  HIGHLIGHT = 'highlight',
}

export enum Action {
  VIEW = 'view',
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
}
